"""Initial Migration

Revision ID: b1b4b618e741
Revises: 
Create Date: 2024-08-08 18:28:36.943572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision: str = 'b1b4b618e741'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
                    sa.Column('document_identifier', sa.String(length=14), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('company', sa.String(length=255), nullable=True),
                    sa.Column('product_type', sa.String(length=255), nullable=True),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('document_identifier'),
                    sa.UniqueConstraint('document_identifier')
                    )
    op.create_table('debt',
                    sa.Column('operation_identifier', sa.String(length=255), nullable=False),
                    sa.Column('client', sa.String(length=14), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('emition_date', sa.DateTime(), nullable=False),
                    sa.Column('expiration_date', sa.DateTime(), nullable=False),
                    sa.Column('total_debt', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('default_debt', sa.DECIMAL(precision=12, scale=2), nullable=False),
                    sa.Column('administration_expenses', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('minimum_payment', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('period', sa.String(length=2), nullable=False),
                    sa.Column('fee', sa.String(length=2), nullable=False),
                    sa.Column('product_code', sa.String(length=3), nullable=False),
                    sa.Column('currency', sa.String(length=10), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('created_by', sa.String(length=255), nullable=True),
                    sa.Column('date_updated', sa.DateTime(), nullable=True),
                    sa.Column('updated_by', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['client'], ['client.document_identifier'], name='fk_debt_client_document_identifier_client'),
                    sa.PrimaryKeyConstraint('operation_identifier')
                    )
    op.create_table('payment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('debt', sa.String(length=255), nullable=True),
                    sa.Column('emition_date', sa.DateTime(), nullable=False),
                    sa.Column('bank_code', sa.String(length=255), nullable=False),
                    sa.Column('operation_bank_number', sa.String(length=12), nullable=False),
                    sa.Column('gateway', sa.String(length=255), nullable=False),
                    sa.Column('payment_type', sa.String(length=255), nullable=False),
                    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('date_created', sa.DateTime(), nullable=True),
                    sa.Column('date_updated', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['debt'], ['debt.operation_identifier'], name='fk_payment_debt_operation_identifier_debt'),
                    sa.UniqueConstraint('operation_bank_number'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('debt')
    op.drop_table('client')
    # ### end Alembic commands ###
